### ISSUE TITLE
e1017

### ISSUE THREAD

**Issue by flor14** [juliasilge/supervised-ML-case-studies-course#14]
Some exercises are not working linked to this error

Error: package e1071 is required
(ex, Exercise 11 of chapter 2)

When I tried to install this package on binder, everything fails.

**Comment by juliasilge** [comment]
I should have checked this to start this. 🙈 

Here are the packages that build the Docker container on the other platform:

```
install_version("e1071", "1.6-8")
install_version("gbm", "2.1.3")
install_version("randomForest", "4.6-12")
install_version("xgboost", "0.6.4.1")
install_version("caret", "6.0-78")
install_version("yardstick", "0.0.1")
install_version("tidyverse", "1.2.1")
```

Want to try including both **gbm** and **e1071**?

**Comment by juliasilge** [comment]
Right now [install.R](https://github.com/juliasilge/supervised-ML-case-studies-course/blob/master/binder/install.R) references a **glm** package but I think that is a typo?

**Comment by juliasilge** [comment]
Looks like this package is installed correctly now, and 4.11 is working well. 👍
