### ISSUE TITLE
Ch. 4 Part 8 Typo

### ISSUE THREAD

**Issue by pgauding** [juliasilge/supervised-ML-case-studies-course#22]
`sisters_text` at the end should be `sisters_test`, I believe
![Screen Shot 2019-09-23 at 10 51 34 PM](https://user-images.githubusercontent.com/4986067/65479848-bb269d80-de54-11e9-8502-319680c336a6.png)

**Comment by pgauding** [comment]
Not sure if text came through, but `sisters_text` should read `sisters_test`, I believe.

**Comment by juliasilge** [comment]
Thank you so much for this report @pgauding! 🙌
