### ISSUE TITLE
Ch. 4 Part 10 Type

### ISSUE THREAD

**Issue by pgauding** [juliasilge/supervised-ML-case-studies-course#23]
![Screen Shot 2019-09-23 at 11 03 18 PM](https://user-images.githubusercontent.com/4986067/65480250-64ba5e80-de56-11e9-84ea-a95916fefdb2.png)
"If you stop 🛑 to think aout" should read If you stop 🛑 to think about"

**Comment by juliasilge** [comment]
🛑 Thank you so much! 🛑
