### ISSUE TITLE
Cannot download file 

### ISSUE THREAD

**Issue by siamsoft2020** [juliasilge/supervised-ML-case-studies-course#26]
Cannot download file cl_cars_vars_full.rds.  An  error page is thrown.

Thanks.

**Comment by juliasilge** [comment]
Hello there @siamsoft2020! Thanks so much for checking out the course.

Are you talking about exercise 6 in Chapter 1? The file there is `c1_cars_vars_full.rds`, with a `1` not an `l`. You shouldn't need to retype any of that, as it is already part of the code that is given to you.

This exercise appears to be working for me:

![Screen Shot 2019-09-28 at 9 30 22 PM](https://user-images.githubusercontent.com/12505835/65825708-5fcf2380-e237-11e9-89f7-b96b02571994.png)

Can you give me a little more info on what kind of problem you are seeing?

**Comment by juliasilge** [comment]
Let me know if you are still getting this error @siamsoft2020, even after checking the filename! I'll close this issue for now. 👍
