### ISSUE TITLE
Where do I put the data files for the course?

### ISSUE THREAD

**Issue by juliasilge** [juliasilge/supervised-ML-case-studies-course#3]
The code bits, such as in [this exercise](https://github.com/juliasilge/supervised-ML-case-studies-course/blob/master/exercises/exc_01_03.R) use files that I created ahead of time with datasets. I don't see these files anywhere in the repo right now. Where do I put them? How will they be made accessible when Binder launches?

**Comment by juliasilge** [comment]
Hello @flor14! 👋 I now have the repo public and I have started trying to get [Binder up and running here](https://mybinder.org/v2/gh/juliasilge/supervised-ML-case-studies-course/binder). Nothing is happening?!? I don't even have anything in the logs. 😕 

What do you think we should try next to get this working?

**Comment by flor14** [comment]
Hello! 😊

If you have already used binder, you should try to deploy the course with netlify.
The code in the exercises should run after deployment.


Tell me if I can help
Best,
Florencia

Sent from Mail for Windows 10

**Comment by juliasilge** [comment]
OK, I think it is ✨ actually working ✨.
https://supervised-ml-course.netlify.com/

It looks to me like the exercises are running! So the next step is for both of us to do a final check that the exercises are running as expected, I believe?

**Comment by flor14** [comment]
🎉 Great news!!!! 🥳

Yes, final step! I will have a look and tell you.

I like all the emojis you added to the course 👍

Best
Florencia

Sent from Mail for Windows 10
