### ISSUE TITLE
Chapter 4, Exercise 13: xgboost performing better than GBM 

### ISSUE THREAD

**Issue by johncassil** [juliasilge/supervised-ML-case-studies-course#31]
Hey Julia!

THANK YOU SO MUCH for an amazing course.  I have been impressed end to end and I am definitely going to share it with a bunch of folks.

I got tripped up on something and wanted to see if it's a mistake, maybe with the saved model RDS, or updated default parameters.  

In Chapter 4, Exercise 13, the rmse for the xgboost predictions (12.3472006) is smaller than the rmse for GBM predictions (12.4721538), but the lesson goes on to say that GBM performed the best.

You can test by going to https://supervised-ml-course.netlify.com/chapter4 in incognito mode, click "Show solution" and "Run Code":

![input](https://user-images.githubusercontent.com/1057388/65798951-fbca3380-e140-11e9-8e9d-4659d58d4e39.PNG)
![output](https://user-images.githubusercontent.com/1057388/65798956-fd93f700-e140-11e9-9ab7-4e26fe1e1ad5.PNG)

Please let me know if I can help with a fix!

**Comment by juliasilge** [comment]
Thank you so much for this report @johncassil! 🙌 I appreciate it a lot. 

I believe I have found all the places/ways this needs to be edited/corrected, but certainly if you noticed anything else, please let me know.
