### ISSUE TITLE
Chapter 1, Exercise 5, Slide 5 - variable continuity

### ISSUE THREAD

**Issue by kaboroevich** [juliasilge/supervised-ML-case-studies-course#46]
A very finicky point, but I mention it for continuity. Through the rest of the chapter, the variables for the training and testing set are "car_train" and "car_test", respectively, but on this slide, "car_training" and "car_testing" are used.

**Comment by juliasilge** [comment]
Thank you for the feedback! 🙌  I appreciate it.
