### ISSUE TITLE
Confusing name of variable

### ISSUE THREAD

**Issue by noeliarico** [juliasilge/supervised-ML-case-studies-course#51]
Hi,

in the 4th case of study, the section "4 - tidy the survey data" says:

- _Group by age and summarize the `value` column to see how the overall agreement with all questions varied by age._
- _Count the `value` column to check out how many respondents agreed or disagreed overall._

The real name of the variable is `rating` and not `value`, as it was the name given to it in the `pivot_longer()` of the previous chunk of code. I realized later that probably `value` is written on purpose to emphasize that it is the column containing the value and not the key. Anyway, as this is written with then syntax usually used for literal names of variables, it seems a little bit confusing, at least to me.

Great course! :)

**Comment by juliasilge** [comment]
Thank you so much @noeliarico! 🙌  I changed these variable names in the exercises but missed them in the narrative/instructions.
