### ISSUE TITLE
Chapter 2 - recipes::step_downsample is deprecated

### ISSUE THREAD

**Issue by davidski** [juliasilge/supervised-ML-case-studies-course#52]
Chapter 2 is calling `recipes::step_downsample()` which is now deprecated in favor of `themis::step_downsample()`, for users running current tidymodels versions locally. A simple call to `library(themis)` in the setup should quiet this problem. :smile: Thanks for making this course available!

**Comment by juliasilge** [comment]
Thank you so much @davidski! 🚀
