### ISSUE TITLE
Chapter 3.6 Error in initial_split when running locally

### ISSUE THREAD

**Issue by gabegarcia15** [juliasilge/supervised-ML-case-studies-course#61]
Love the tidymodels course! 

I came across an error when running the following code snippet in chapter 3.6 locally.

```
vote_split <- voters_select %>%
    initial_split(p = 0.8,
                  strata = turnout16_2016)
```

`Error in initial_split(., p = 0.8, strata = turnout16_2016, ) : 
  argument 2 matches multiple formal arguments`

When I changed the code snippet to the following, everything worked as expected:

```
vote_split <- voters_select %>%
    initial_split(prop = 0.8,
                  strata = turnout16_2016)
```

I'm not sure if "p" was an accepted abbreviation of "prop" previously, but changing "p" to "prop" fixed the error

**Comment by juliasilge** [comment]
Thank you so much @gabegarcia15! 🙌 

I believe this is now fixed throughout the course and [updated in the Binder for this repo](https://mybinder.org/v2/gh/juliasilge/supervised-ML-case-studies-course/binder). If you find any further problems, let me know.
